Sprint 12
kkkyifut/ImageFeed pull request #5
Opened 2023-01-29 10:23 UTC by kkkyifut

2023-01-29 14:05 UTC, IBDesignable requested changes

2023-01-29 19:25 UTC, IBDesignable commented
В классе авторизации есть вот такой код:
 ```swift
 func webViewViewController(_ vc: WebViewViewController, didAuthenticateWithCode code: String) {
        guard storageToken.token == nil else { return }
        UIBlockingProgressHUD.show()
        OAuth2Service.shared.fetchAuthToken(code: code) { result in
            DispatchQueue.main.async { [self] in
                do {
                    let data = try result.get()
                    storageToken.token = data
                    self.fetchProfile(token: storageToken.token!)
                    UIBlockingProgressHUD.dismiss()
                } catch let error {
                    print("Error: ", error)
                    UIBlockingProgressHUD.dismiss()
                }
            }
        }
// следующий код вызовется не дожидаясь  сохранения токена, 
// подргузки профиля, изображения. 
 // Лента не будет прогружена, это ошибка 
        let tabBarViewController = storyboardInstance.instantiateViewController(withIdentifier: "TabBarViewController") 

        UIApplication.shared.windows.first?.rootViewController = tabBarViewController
        UIApplication.shared.windows.first?.makeKeyAndVisible()
    }
```

2023-01-29 19:30 UTC, IBDesignable commented
Слой анимации сделан круто, в том месте, где ты выносишь это в хелпер, и реализуешь чистой функцией. 

Чтобы это работало, надо учитывать особенность работы слоев. Им нужны не только размеры, но и точка относительно которой будешь начинать строить отображение `origin: .zero,` – неплохо для этой функции, но ожидаемо, отображаться будет в "какой-то" нулевой точке. давай при наложении слоя, еще поправлять frame на валидный. Иначе будем видеть не то, что хотим (скрин ниже)

```
  func createGradient(width: CGFloat, height: CGFloat, cornerRadius: CGFloat) -> CAGradientLayer {
        let gradient = CAGradientLayer()
        gradient.frame = CGRect(origin: .zero, size: CGSize(width: width, height: height))
        gradient.locations = [0, 0.1, 0.3]
        gradient.colors = [
            UIColor(red: 0.682, green: 0.686, blue: 0.706, alpha: 1).cgColor,
            UIColor(red: 0.531, green: 0.533, blue: 0.553, alpha: 1).cgColor,
            UIColor(red: 0.431, green: 0.433, blue: 0.453, alpha: 1).cgColor
        ]
        gradient.startPoint = CGPoint(x: 0, y: 0.5)
        gradient.endPoint = CGPoint(x: 1, y: 0.5)
        gradient.cornerRadius = cornerRadius
        gradient.masksToBounds = true
        
        let gradientChangeAnimation = CABasicAnimation(keyPath: "locations")
        gradientChangeAnimation.duration = 1.0
        gradientChangeAnimation.repeatCount = .infinity
        gradientChangeAnimation.fromValue = [0, 0.1, 0.3]
        gradientChangeAnimation.toValue = [0, 0.8, 1]
        gradient.add(gradientChangeAnimation, forKey: "locationsChange")
        
        return gradient
    }
```
<img width="511" alt="Снимок экрана 2023-01-29 в 21 19 36" src="https://user-images.githubusercontent.com/121577115/215351089-dd62fdf1-e7f5-4c32-98d2-37a0b673ed74.png">

2023-01-29 19:31 UTC, IBDesignable requested changes

2023-01-29 19:31 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +            self.lastLoadedPage! += 1
оу, да, мой вариант оказался не таким уж и хорошим, так как переопредляет имя переменной, но даже так var - не нужен, и опционал тоже. 
```suggestion
        if lastLoadedPage != nil {
            lastLoadedPage += 1
```

2023-01-29 19:31 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService.swift
> +        let token = storageToken.token ?? ""
Зачем делать запрос, если пустая строка вместо токена приведет к ошибке? лучше совсем не делать запрос и вернуть ошибку.

2023-01-29 19:39 UTC, IBDesignable commented on ImageFeed/Helper/AnimationGradient.swift
> +class AnimationGradient {
я по названию думала что это вьюха с градиентом, но на деле это что-то вроде фабрики. Поэтому так бы и назвала AnimationGradientFactory/AnimationGradientCreator

2023-01-29 19:39 UTC, IBDesignable commented on ImageFeed/Helper/AnimationGradient.swift
> +    }
а эту функцию бы удалила, и делала тоже самое рядом с местом удаления

2023-01-29 19:39 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        cell.layer.addSublayer(gradient)
очень странно, что только градиент один используется для всех ячеек. Это ссылочный тип, и вероятно это не будет работать "как копия" на каждом слое. 

Тебе нужно создавать новый слой, обновлять ему размер и origin здесь

2023-01-30 08:18 UTC, kkkyifut commented on ImageFeed/Services/ImagesListService.swift
> +            self.lastLoadedPage! += 1
Без опционала не обойтись

2023-02-01 18:37 UTC, merged